version: "3"
services: 
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  gateway: 
    image: minio/minio
    command: gateway nas /data
    ports: 
    - "9000:9000"
    environment:
    - "MINIO_ACCESS_KEY=dalongapp"
    - "MINIO_SECRET_KEY=dalongapp"
    - "MINIO_PROMETHEUS_AUTH_TYPE=public"
    volumes: 
    - "./data:/data"
  gateway2: 
    image: minio/minio
    command:  gateway s3 http://gateway:9000
    ports: 
    - "9001:9000"
    environment:
    - "MINIO_ACCESS_KEY=dalongapp"
    - "MINIO_SECRET_KEY=dalongapp"
    - "MINIO_PROMETHEUS_AUTH_TYPE=public"
