scrape_configs:
  - job_name: gateway
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['gateway:9000']
  - job_name: gateway2
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['gateway2:9000']